version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: |
          echo $GCP_PROJECT_KEY
          gcloud auth activate-service-account --key-file=key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud app deploy
workflows:
  ci:
    jobs:
      - build-and-test
      - deploy:
          context: elgnim-prod
          requires:
            - build-and-test
