version: 2.1
orbs:
  node: circleci/node@1.1.6
  gcp-cli: circleci/gcp-cli@1.8.4
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  push-to-gcloud:
      executor: gcp-cli/default
      steps:
        - run: install_and_initialize_cli
        - run: gcloud app deploy

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - push-to-gcloud
